VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "TextWriter"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
'    CopyRight (c) 2005 Kelly Ethridge
'
'    This file is part of VBCorLib.
'
'    VBCorLib is free software; you can redistribute it and/or modify
'    it under the terms of the GNU Library General Public License as published by
'    the Free Software Foundation; either version 2.1 of the License, or
'    (at your option) any later version.
'
'    VBCorLib is distributed in the hope that it will be useful,
'    but WITHOUT ANY WARRANTY; without even the implied warranty of
'    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
'    GNU Library General Public License for more details.
'
'    You should have received a copy of the GNU Library General Public License
'    along with Foobar; if not, write to the Free Software
'    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
'
'    Module: TextWriter
'
Option Explicit

Public Property Get Encoding() As Encoding: End Property
Public Property Get FormatProvider() As IFormatProvider: End Property
Public Property Get NewLine() As String: End Property
Public Property Let NewLine(ByVal RHS As String): End Property
Public Sub CloseWriter(): End Sub
Public Function Equals(ByRef value As Variant) As Boolean: End Function
Public Sub Flush(): End Sub
Public Function GetHashCode() As Long: End Function
Public Function ToString() As String: End Function
Public Sub WriteValue(ByRef value As Variant, ParamArray args() As Variant): End Sub
Public Sub WriteLine(ParamArray value() As Variant): End Sub

